package entity

import (
	"fmt"
	"os"
	"strings"

	"github.com/MaminirinaEdwino/turbostack/src/config"
)

func (mgr *ProjectManager) gormModelExporter(models []Model, projectName string) {
	for _, model := range models {
		mName := model.GetNom()
		if mName == "" {
			continue
		}

		// Chemin du fichier : turbo_projects/nom_projet/models/nom_model.go
		filePath := fmt.Sprintf("%s/%s/models/%s.go", config.PROJECT_DIR, projectName, strings.ToLower(mName))

		file, err := os.Create(filePath)
		if err != nil {
			fmt.Printf("Erreur lors de la création du fichier %s : %v\n", filePath, err)
			continue
		}

		// Construction du contenu du fichier
		var sb strings.Builder
		sb.WriteString("package models\n\n")

		// Nom de la struct (Première lettre en majuscule pour l'exportation)
		structName := strings.ToUpper(mName[:1]) + mName[1:]
		fmt.Fprintf(&sb, "type %s struct {\n", structName)

		for _, field := range model.GetAttributs() {
			fieldName := strings.ToUpper(field.GetNom()[:1]) + field.GetNom()[1:]

			// Mapping des types simples
			goType := "string"
			switch strings.ToLower(field.GetType()) {
			case "int":
				goType = "int"
			case "string", "text":
				goType = "string"
			}

			// Traduction des contraintes en tags GORM
			gormTag := mgr.generateGormTags(field)

			fmt.Fprintf(&sb, "\t%s %s %s\n", fieldName, goType, gormTag)
		}

		sb.WriteString("}\n")

		file.WriteString(sb.String())
		file.Close()
	}
}

func (mgr *ProjectManager) postgresSQLExporter(models []Model, projectName string) {
	filePath := fmt.Sprintf("%s/%s/models/init_db.sql", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Erreur lors de la création du script SQL %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("-- SQL Schema for PostgreSQL\n")
	sb.WriteString("-- Generated by TurboStack\n\n")

	for _, model := range models {
		tableName := strings.ToLower(model.GetNom())
		sb.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", tableName))

		var columns []string
		for i, field := range model.GetAttributs() {
			fName := strings.ToLower(field.GetNom())
			fType := strings.ToLower(field.GetType())

			// Détection de l'autoincrement pour le type SERIAL
			isSerial := false
			constraints := field.GetConstraint()
			for _, c := range constraints {
				if strings.ToLower(fmt.Sprintf("%v", c)) == "autoincrement" {
					isSerial = true
					break
				}
			}

			// Mapping des types PG
			pgType := "TEXT"
			switch fType {
			case "int":
				if isSerial {
					pgType = "SERIAL"
				} else {
					pgType = "INTEGER"
				}
			case "string":
				pgType = "VARCHAR(255)"
			}

			colDef := fmt.Sprintf("\t%s %s", fName, pgType)

			// Ajout des contraintes
			for _, c := range constraints {
				cStr := strings.ToLower(fmt.Sprintf("%v", c))
				switch cStr {
				case "primary key":
					colDef += " PRIMARY KEY"
				case "unique":
					colDef += " UNIQUE"
				case "not null":
					colDef += " NOT NULL"
				}

				if strings.HasPrefix(cStr, "relation:") {
					target := strings.Split(cStr, ":")[1] // ex: user.id
					targetParts := strings.Split(target, ".")
					if len(targetParts) == 2 {
						colDef += fmt.Sprintf(" REFERENCES %s(%s)", targetParts[0], targetParts[1])
					}
				}
			}
			columns = append(columns, colDef)
			_ = i
		}
		sb.WriteString(strings.Join(columns, ",\n"))
		sb.WriteString("\n);\n\n")
	}

	file.WriteString(sb.String())
}

func (mgr *ProjectManager) postgresCRUDExporter(models []Model, projectName string) {
	filePath := fmt.Sprintf("%s/%s/models/crud_queries.sql", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Erreur lors de la création du script CRUD %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("-- CRUD and Join Queries for PostgreSQL\n")
	sb.WriteString("-- Generated by TurboStack\n\n")

	for _, model := range models {
		tableName := strings.ToLower(model.GetNom())
		fields := model.GetAttributs()
		var colNames []string
		var pkName string

		for _, field := range fields {
			name := strings.ToLower(field.GetNom())
			colNames = append(colNames, name)
			for _, c := range field.GetConstraint() {
				if strings.ToLower(fmt.Sprintf("%v", c)) == "primary key" {
					pkName = name
				}
			}
		}

		if pkName == "" && len(colNames) > 0 {
			pkName = colNames[0]
		}

		fmt.Fprintf(&sb, "-- Queries for table: %s\n", tableName)

		// Create (Insert)
		placeholders := make([]string, len(colNames))
		for i := range colNames {
			placeholders[i] = fmt.Sprintf("$%d", i+1)
		}
		fmt.Fprintf(&sb, "-- Create\nINSERT INTO %s (%s) VALUES (%s);\n\n",
			tableName, strings.Join(colNames, ", "), strings.Join(placeholders, ", "))

		// Read (Select by ID)
		fmt.Fprintf(&sb, "-- Read\nSELECT * FROM %s WHERE %s = $1;\n\n", tableName, pkName)

		// Update
		var updates []string
		for i, col := range colNames {
			updates = append(updates, fmt.Sprintf("%s = $%d", col, i+1))
		}
		fmt.Fprintf(&sb, "-- Update\nUPDATE %s SET %s WHERE %s = $%d;\n\n",
			tableName, strings.Join(updates, ", "), pkName, len(colNames)+1)

		// Delete
		fmt.Fprintf(&sb, "-- Delete\nDELETE FROM %s WHERE %s = $1;\n\n", tableName, pkName)

		// Joins basés sur les contraintes de relation
		for _, field := range fields {
			for _, c := range field.GetConstraint() {
				cStr := strings.ToLower(fmt.Sprintf("%v", c))
				if strings.HasPrefix(cStr, "relation:") {
					target := strings.Split(cStr, ":")[1]
					targetParts := strings.Split(target, ".")
					if len(targetParts) == 2 {
						targetTable := targetParts[0]
						targetCol := targetParts[1]
						fmt.Fprintf(&sb, "-- Join with %s\nSELECT t1.*, t2.* FROM %s t1 JOIN %s t2 ON t1.%s = t2.%s;\n\n",
							targetTable, tableName, targetTable, strings.ToLower(field.GetNom()), targetCol)
					}
				}
			}
		}
		sb.WriteString("\n")
	}
	file.WriteString(sb.String())
}

func (mgr *ProjectManager) ExporterDB(Project Project) {
	db := Project.GetBDD()
	models := db.GetModels()
	projectName := Project.GetNom()
	mgr.gormModelExporter(models, projectName)
	mgr.postgresSQLExporter(models, projectName)
	mgr.postgresCRUDExporter(models, projectName)
	fmt.Printf("Exportation des modèles terminée pour le projet : %s\n", projectName)
}

func (mgr *ProjectManager) setupFileArch(name string) {
	projectPath := fmt.Sprintf("%s/api/", name)
	dirList := []string{
		"src/config",
		"src/controllers",
		"src/middlewares",
		"src/routes",
		"src/models/gorm",
		"src/models/pg",
	}
	for _, val := range dirList {
		config.CheckCreateDir(projectPath + val)
	}
}

func (mgr *ProjectManager) ExporterAPI(Project Project) {
	projectName := Project.GetNom()
	bdd := Project.GetBDD()
	mgr.setupFileArch(projectName)
	models := bdd.GetModels()

	// Exportation des modèles pour les deux ORM/Librairies
	mgr.gormAPIModelExporter(models, projectName)
	mgr.pgAPIModelExporter(models, projectName)

	fmt.Printf("Exportation de l'API terminée pour le projet : %s\n", projectName)
}

// gormAPIModelExporter exporte les modèles avec les tags GORM dans src/models/gorm
func (mgr *ProjectManager) gormAPIModelExporter(models []Model, projectName string) {
	for _, model := range models {
		mName := model.GetNom()
		if mName == "" {
			continue
		}

		filePath := fmt.Sprintf("%s/%s/api/src/models/gorm/%s.go", config.PROJECT_DIR, projectName, strings.ToLower(mName))
		file, err := os.Create(filePath)
		if err != nil {
			fmt.Printf("Erreur lors de la création du fichier GORM %s : %v\n", filePath, err)
			continue
		}

		var sb strings.Builder
		sb.WriteString("package gorm\n\n")
		structName := strings.ToUpper(mName[:1]) + mName[1:]
		fmt.Fprintf(&sb, "type %s struct {\n", structName)

		for _, field := range model.GetAttributs() {
			fieldName := strings.ToUpper(field.GetNom()[:1]) + field.GetNom()[1:]
			goType := mgr.mapToGoType(field.GetType())
			gormTag := mgr.generateGormTags(field)
			fmt.Fprintf(&sb, "\t%s %s %s\n", fieldName, goType, gormTag)
		}
		sb.WriteString("}\n")
		file.WriteString(sb.String())
		file.Close()
	}
}

// pgAPIModelExporter exporte les modèles avec les tags pour go-pg dans src/models/pg
func (mgr *ProjectManager) pgAPIModelExporter(models []Model, projectName string) {
	for _, model := range models {
		mName := model.GetNom()
		if mName == "" {
			continue
		}

		filePath := fmt.Sprintf("%s/%s/api/src/models/pg/%s.go", config.PROJECT_DIR, projectName, strings.ToLower(mName))
		file, err := os.Create(filePath)
		if err != nil {
			fmt.Printf("Erreur lors de la création du fichier PG %s : %v\n", filePath, err)
			continue
		}

		var sb strings.Builder
		sb.WriteString("package pg\n\n")
		structName := strings.ToUpper(mName[:1]) + mName[1:]
		fmt.Fprintf(&sb, "type %s struct {\n", structName)

		for _, field := range model.GetAttributs() {
			fieldName := strings.ToUpper(field.GetNom()[:1]) + field.GetNom()[1:]
			goType := mgr.mapToGoType(field.GetType())
			pgTag := mgr.generatePgTags(field)
			fmt.Fprintf(&sb, "\t%s %s %s\n", fieldName, goType, pgTag)
		}
		sb.WriteString("}\n")
		file.WriteString(sb.String())
		file.Close()
	}
}

// mapToGoType convertit les types UI en types Go
func (mgr *ProjectManager) mapToGoType(uiType string) string {
	switch strings.ToLower(uiType) {
	case "int":
		return "int"
	case "string", "text":
		return "string"
	default:
		return "string"
	}
}

func (mgr *ProjectManager) ExporterStaticSite(Project Project) {
	fmt.Println("static site")
}
func (mgr *ProjectManager) ExporterWebApp(Project Project) {
	fmt.Println("web app")
}

// generateGormTags transforme les contraintes de l'UI en chaîne de tags GORM
func (mgr *ProjectManager) generateGormTags(field Champs) string {
	var tags []string

	for _, c := range field.GetConstraint() {
		cStr := strings.ToLower(fmt.Sprintf("%v", c))

		switch cStr {
		case "primary key":
			tags = append(tags, "primaryKey")
		case "unique":
			tags = append(tags, "unique")
		case "not null":
			tags = append(tags, "not null")
		case "autoincrement":
			tags = append(tags, "autoIncrement")
		}

		if strings.HasPrefix(cStr, "relation:") {
			// Pour les relations, on peut indexer le champ automatiquement
			tags = append(tags, "index")
		}
	}

	if field.GetDefaultValue() != nil && field.GetDefaultValue() != "" {
		tags = append(tags, fmt.Sprintf("default:%v", field.GetDefaultValue()))
	}

	if len(tags) > 0 {
		return fmt.Sprintf("`gorm:\"%s\"`", strings.Join(tags, ";"))
	}
	return ""
}

// generatePgTags transforme les contraintes en chaîne de tags pour la lib go-pg
func (mgr *ProjectManager) generatePgTags(field Champs) string {
	var tags []string
	for _, c := range field.GetConstraint() {
		cStr := strings.ToLower(fmt.Sprintf("%v", c))
		switch cStr {
		case "primary key":
			tags = append(tags, "pk")
		case "unique":
			tags = append(tags, "unique")
		case "not null":
			tags = append(tags, "notnull")
		}
	}

	if field.GetDefaultValue() != nil && field.GetDefaultValue() != "" {
		tags = append(tags, fmt.Sprintf("default:%v", field.GetDefaultValue()))
	}

	if len(tags) > 0 {
		return fmt.Sprintf("`pg:\",%s\"`", strings.Join(tags, ","))
	}
	return ""
}
