package entity

import (
	"fmt"
	"os"
	"strings"

	"github.com/MaminirinaEdwino/turbostack/src/config"
)

func (mgr *ProjectManager) gormModelExporter(models []Model, projectName string) {
	for _, model := range models {
		mName := model.GetNom()
		if mName == "" {
			continue
		}

		// Chemin du fichier : turbo_projects/nom_projet/models/nom_model.go
		filePath := fmt.Sprintf("%s/%s/models/%s.go", config.PROJECT_DIR, projectName, strings.ToLower(mName))

		file, err := os.Create(filePath)
		if err != nil {
			fmt.Printf("Erreur lors de la création du fichier %s : %v\n", filePath, err)
			continue
		}

		// Construction du contenu du fichier
		var sb strings.Builder
		sb.WriteString("package models\n\n")

		// Nom de la struct (Première lettre en majuscule pour l'exportation)
		structName := strings.ToUpper(mName[:1]) + mName[1:]
		fmt.Fprintf(&sb, "type %s struct {\n", structName)

		for _, field := range model.GetAttributs() {
			fieldName := strings.ToUpper(field.GetNom()[:1]) + field.GetNom()[1:]

			// Mapping des types simples
			goType := "string"
			switch strings.ToLower(field.GetType()) {
			case "int":
				goType = "int"
			case "string", "text":
				goType = "string"
			}

			// Traduction des contraintes en tags GORM
			gormTag := mgr.generateGormTags(field)

			fmt.Fprintf(&sb, "\t%s %s %s\n", fieldName, goType, gormTag)
		}

		sb.WriteString("}\n")

		file.WriteString(sb.String())
		file.Close()
	}
}

func (mgr *ProjectManager) postgresSQLExporter(models []Model, projectName string) {
	filePath := fmt.Sprintf("%s/%s/models/init_db.sql", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Erreur lors de la création du script SQL %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("-- SQL Schema for PostgreSQL\n")
	sb.WriteString("-- Generated by TurboStack\n\n")

	for _, model := range models {
		tableName := strings.ToLower(model.GetNom())
		sb.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", tableName))

		var columns []string
		for i, field := range model.GetAttributs() {
			fName := strings.ToLower(field.GetNom())
			fType := strings.ToLower(field.GetType())

			// Détection de l'autoincrement pour le type SERIAL
			isSerial := false
			constraints := field.GetConstraint()
			for _, c := range constraints {
				if strings.ToLower(fmt.Sprintf("%v", c)) == "autoincrement" {
					isSerial = true
					break
				}
			}

			// Mapping des types PG
			pgType := "TEXT"
			switch fType {
			case "int":
				if isSerial {
					pgType = "SERIAL"
				} else {
					pgType = "INTEGER"
				}
			case "string":
				pgType = "VARCHAR(255)"
			}

			colDef := fmt.Sprintf("\t%s %s", fName, pgType)

			// Ajout des contraintes
			for _, c := range constraints {
				cStr := strings.ToLower(fmt.Sprintf("%v", c))
				switch cStr {
				case "primary key":
					colDef += " PRIMARY KEY"
				case "unique":
					colDef += " UNIQUE"
				case "not null":
					colDef += " NOT NULL"
				}

				if strings.HasPrefix(cStr, "relation:") {
					target := strings.Split(cStr, ":")[1] // ex: user.id
					targetParts := strings.Split(target, ".")
					if len(targetParts) == 2 {
						colDef += fmt.Sprintf(" REFERENCES %s(%s)", targetParts[0], targetParts[1])
					}
				}
			}
			columns = append(columns, colDef)
			_ = i
		}
		sb.WriteString(strings.Join(columns, ",\n"))
		sb.WriteString("\n);\n\n")
	}

	file.WriteString(sb.String())
}

func (mgr *ProjectManager) postgresCRUDExporter(models []Model, projectName string) {
	filePath := fmt.Sprintf("%s/%s/models/crud_queries.sql", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Erreur lors de la création du script CRUD %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("-- CRUD and Join Queries for PostgreSQL\n")
	sb.WriteString("-- Generated by TurboStack\n\n")

	for _, model := range models {
		tableName := strings.ToLower(model.GetNom())
		fields := model.GetAttributs()
		var colNames []string
		var pkName string

		for _, field := range fields {
			name := strings.ToLower(field.GetNom())
			colNames = append(colNames, name)
			for _, c := range field.GetConstraint() {
				if strings.ToLower(fmt.Sprintf("%v", c)) == "primary key" {
					pkName = name
				}
			}
		}

		if pkName == "" && len(colNames) > 0 {
			pkName = colNames[0]
		}

		fmt.Fprintf(&sb, "-- Queries for table: %s\n", tableName)

		// Create (Insert)
		placeholders := make([]string, len(colNames))
		for i := range colNames {
			placeholders[i] = fmt.Sprintf("$%d", i+1)
		}
		fmt.Fprintf(&sb, "-- Create\nINSERT INTO %s (%s) VALUES (%s);\n\n",
			tableName, strings.Join(colNames, ", "), strings.Join(placeholders, ", "))

		// Read (Select by ID)
		fmt.Fprintf(&sb, "-- Read\nSELECT * FROM %s WHERE %s = $1;\n\n", tableName, pkName)

		// Update
		var updates []string
		for i, col := range colNames {
			updates = append(updates, fmt.Sprintf("%s = $%d", col, i+1))
		}
		fmt.Fprintf(&sb, "-- Update\nUPDATE %s SET %s WHERE %s = $%d;\n\n",
			tableName, strings.Join(updates, ", "), pkName, len(colNames)+1)

		// Delete
		fmt.Fprintf(&sb, "-- Delete\nDELETE FROM %s WHERE %s = $1;\n\n", tableName, pkName)

		// Joins basés sur les contraintes de relation
		for _, field := range fields {
			for _, c := range field.GetConstraint() {
				cStr := strings.ToLower(fmt.Sprintf("%v", c))
				if strings.HasPrefix(cStr, "relation:") {
					target := strings.Split(cStr, ":")[1]
					targetParts := strings.Split(target, ".")
					if len(targetParts) == 2 {
						targetTable := targetParts[0]
						targetCol := targetParts[1]
						fmt.Fprintf(&sb, "-- Join with %s\nSELECT t1.*, t2.* FROM %s t1 JOIN %s t2 ON t1.%s = t2.%s;\n\n",
							targetTable, tableName, targetTable, strings.ToLower(field.GetNom()), targetCol)
					}
				}
			}
		}
		sb.WriteString("\n")
	}
	file.WriteString(sb.String())
}

func (mgr *ProjectManager) ExporterDB(Project Project) {
	db := Project.GetBDD()
	models := db.GetModels()
	projectName := Project.GetNom()
	mgr.gormModelExporter(models, projectName)
	mgr.postgresSQLExporter(models, projectName)
	mgr.postgresCRUDExporter(models, projectName)
	fmt.Printf("Exportation des modèles terminée pour le projet : %s\n", projectName)
}

func (mgr *ProjectManager) setupFileArch(name string) {
	projectPath := fmt.Sprintf("%s/api/", name)
	dirList := []string{
		"src/config",
		"src/controllers",
		"src/middlewares",
		"src/routes",
		"src/models",
	}
	for _, val := range dirList {
		config.CheckCreateDir(projectPath + val)
	}
}

func (mgr *ProjectManager) ExporterAPI(Project Project) {
	projectName := Project.GetNom()
	bdd := Project.GetBDD()
	mgr.setupFileArch(projectName)
	models := bdd.GetModels()
	api := Project.GetRestApi()

	// Exportation des modèles simplifiés (Structs Go)
	mgr.modelAPIExporter(models, projectName)

	// Exportation des controllers basés sur les endpoints
	mgr.controllerAPIExporter(api.GetEndpoints(), projectName)

	// Exportation des routes groupées par modèles
	mgr.routesAPIExporter(api.GetEndpoints(), projectName)

	// Exportation de la configuration de la base de données
	mgr.configAPIExporter(projectName)

	// Exportation des middlewares (CORS)
	mgr.middlewareAPIExporter(projectName)

	// Exportation du fichier main.go
	mgr.mainAPIExporter(api.GetEndpoints(), projectName)

	fmt.Printf("Exportation de l'API terminée pour le projet : %s\n", projectName)
}

// modelAPIExporter exporte les modèles en tant que structs Go simples dans src/models
func (mgr *ProjectManager) modelAPIExporter(models []Model, projectName string) {
	for _, model := range models {
		mName := model.GetNom()
		if mName == "" {
			continue
		}
		n := strings.ReplaceAll(mName, " ", "_")
		filePath := fmt.Sprintf("%s/%s/api/src/models/%s.go", config.PROJECT_DIR, projectName, strings.ToLower(n))
		file, err := os.Create(filePath)
		if err != nil {
			fmt.Printf("Error creating model file %s : %v\n", filePath, err)
			continue
		}

		var sb strings.Builder
		sb.WriteString("package models\n\n")
		structName := strings.ToUpper(mName[:1]) + mName[1:]
		fmt.Fprintf(&sb, "type %s struct {\n", structName)

		for _, field := range model.GetAttributs() {
			fieldName := strings.ToUpper(field.GetNom()[:1]) + field.GetNom()[1:]
			goType := mgr.mapToGoType(field.GetType())
			fmt.Fprintf(&sb, "\t%s %s `json:\"%s\"`\n", fieldName, goType, strings.ToLower(field.GetNom()))
		}
		sb.WriteString("}\n")
		file.WriteString(sb.String())
		file.Close()
	}
}

// mapToGoType convertit les types UI en types Go
func (mgr *ProjectManager) mapToGoType(uiType string) string {
	switch strings.ToLower(uiType) {
	case "int":
		return "int"
	case "string", "text":
		return "string"
	default:
		return "string"
	}
}

func (mgr *ProjectManager) controllerAPIExporter(endpoints []Endpoint, projectName string) {
	for _, ep := range endpoints {
		eName := ep.GetNom()
		if eName == "" {
			continue
		}

		filePath := fmt.Sprintf("%s/%s/api/src/controllers/%s.go", config.PROJECT_DIR, projectName, strings.ToLower(strings.ReplaceAll(eName, " ", "_")))
		file, err := os.Create(filePath)
		if err != nil {
			fmt.Printf("Error creating controller %s : %v\n", filePath, err)
			continue
		}

		var sb strings.Builder
		sb.WriteString("package controllers\n\n")
		sb.WriteString("import (\n")
		sb.WriteString("\t\"encoding/json\"\n")
		sb.WriteString("\t\"net/http\"\n")
		sb.WriteString("\t\"src/models\"\n")
		sb.WriteString("\t\"src/config\"\n")
		sb.WriteString("\t_ \"github.com/lib/pq\"\n")
		sb.WriteString(")\n\n")

		funcName := strings.ToUpper(eName[:1]) + eName[1:]

		// Identification du modèle associé
		var activeModel Model
		if len(ep.GetModel()) > 0 {
			activeModel = ep.GetModel()[0]
		}
		modelName := activeModel.GetNom()

		fmt.Fprintf(&sb, "// %s handles the %s request for %s\n", funcName, ep.GetMethod(), ep.GetUri())
		fmt.Fprintf(&sb, "func %s(w http.ResponseWriter, r *http.Request) {\n", strings.ReplaceAll(funcName, " ", "_"))

		if modelName != "" {
			structName := strings.ToUpper(modelName[:1]) + modelName[1:]
			tableName := strings.ToLower(modelName)

			var columns []string
			var scanTargets []string
			for _, attr := range activeModel.GetAttributs() {
				columns = append(columns, strings.ToLower(attr.GetNom()))
				scanTargets = append(scanTargets, "&item."+strings.ToUpper(attr.GetNom()[:1])+attr.GetNom()[1:])
			}

			fmt.Fprintf(&sb, "\trows, err := config.DB.Query(\"SELECT %s FROM %s\")\n", strings.Join(columns, ", "), tableName)
			sb.WriteString("\tif err != nil {\n\t\thttp.Error(w, err.Error(), http.StatusInternalServerError)\n\t\treturn\n\t}\n\tdefer rows.Close()\n\n")
			fmt.Fprintf(&sb, "\tvar results []models.%s\n", structName)
			fmt.Fprintf(&sb, "\tfor rows.Next() {\n\t\tvar item models.%s\n", structName)
			fmt.Fprintf(&sb, "\t\tif err := rows.Scan(%s); err != nil {\n\t\t\tcontinue\n\t\t}\n", strings.Join(scanTargets, ", "))
			sb.WriteString("\t\tresults = append(results, item)\n\t}\n")
			sb.WriteString("\tjson.NewEncoder(w).Encode(results)\n")
		} else {
			fmt.Fprintf(&sb, "\tjson.NewEncoder(w).Encode(map[string]string{\"message\": \"%s endpoint reached\"})\n", eName)
		}

		sb.WriteString("}\n")

		file.WriteString(sb.String())
		file.Close()
	}
}

// routesAPIExporter génère le fichier de configuration des routes groupées par modèles
func (mgr *ProjectManager) routesAPIExporter(endpoints []Endpoint, projectName string) {
	filePath := fmt.Sprintf("%s/%s/api/src/routes/routes.go", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Error creating routes file %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("package routes\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"net/http\"\n")
	sb.WriteString("\t\"src/controllers\"\n")
	sb.WriteString(")\n\n")

	// Groupement des endpoints par nom de modèle
	groups := make(map[string][]Endpoint)
	for _, ep := range endpoints {
		mName := "General"
		if len(ep.GetModel()) > 0 {
			mName = ep.GetModel()[0].GetNom()
		}
		groups[mName] = append(groups[mName], ep)
	}

	for groupName, eps := range groups {
		cleanGroupName := strings.ReplaceAll(groupName, " ", "_")
		groupFuncName := strings.ToUpper(cleanGroupName[:1]) + cleanGroupName[1:]
		fmt.Fprintf(&sb, "func RegisterRoutes%s(mux *http.ServeMux) {\n", groupFuncName)
		for _, ep := range eps {
			method := ep.GetMethod()
			uri := ep.GetUri()
			eName := ep.GetNom()
			funcName := strings.ToUpper(eName[:1]) + strings.ReplaceAll(eName[1:], " ", "_")
			fmt.Fprintf(&sb, "\tmux.HandleFunc(\"%s %s\", controllers.%s)\n", method, uri, funcName)
		}
		sb.WriteString("}\n\n")
	}
	file.WriteString(sb.String())
}

// configAPIExporter génère le fichier de configuration pour la connexion à PostgreSQL
func (mgr *ProjectManager) configAPIExporter(projectName string) {
	filePath := fmt.Sprintf("%s/%s/api/src/config/db.go", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Error creating config file %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("package config\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"database/sql\"\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"log\"\n")
	sb.WriteString("\t_ \"github.com/lib/pq\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("var DB *sql.DB\n\n")
	sb.WriteString("// InitDB initialise la connexion à la base de données PostgreSQL\n")
	sb.WriteString("func InitDB() {\n")
	sb.WriteString("\t// Modifiez cette chaîne de connexion selon votre environnement\n")
	sb.WriteString("\tconnStr := \"user=postgres password=root dbname=postgres sslmode=disable host=localhost port=5432\"\n")
	sb.WriteString("\tvar err error\n")
	sb.WriteString("\tDB, err = sql.Open(\"postgres\", connStr)\n")
	sb.WriteString("\tif err != nil {\n\t\tlog.Fatal(err)\n\t}\n\n")
	sb.WriteString("\tif err = DB.Ping(); err != nil {\n\t\tlog.Fatal(err)\n\t}\n\n")
	sb.WriteString("\tfmt.Println(\"Successfully connected to database\")\n")
	sb.WriteString("}\n")

	file.WriteString(sb.String())
}

// middlewareAPIExporter génère un middleware CORS permissif dans src/middlewares/cors.go
func (mgr *ProjectManager) middlewareAPIExporter(projectName string) {
	filePath := fmt.Sprintf("%s/%s/api/src/middlewares/cors.go", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Error creating middleware file %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("package middlewares\n\n")
	sb.WriteString("import \"net/http\"\n\n")
	sb.WriteString("// CorsMiddleware gère les autorisations Cross-Origin (CORS) pour autoriser toutes les sources\n")
	sb.WriteString("func CorsMiddleware(next http.Handler) http.Handler {\n")
	sb.WriteString("\treturn http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {\n")
	sb.WriteString("\t\tw.Header().Set(\"Access-Control-Allow-Origin\", \"*\")\n")
	sb.WriteString("\t\tw.Header().Set(\"Access-Control-Allow-Methods\", \"GET, POST, PUT, DELETE, OPTIONS\")\n")
	sb.WriteString("\t\tw.Header().Set(\"Access-Control-Allow-Headers\", \"Content-Type, Authorization\")\n\n")
	sb.WriteString("\t\tif r.Method == \"OPTIONS\" {\n")
	sb.WriteString("\t\t\tw.WriteHeader(http.StatusOK)\n")
	sb.WriteString("\t\t\treturn\n")
	sb.WriteString("\t\t}\n\n")
	sb.WriteString("\t\tnext.ServeHTTP(w, r)\n")
	sb.WriteString("\t})\n")
	sb.WriteString("}\n")

	file.WriteString(sb.String())
}

// mainAPIExporter génère le point d'entrée principal de l'API (main.go)
func (mgr *ProjectManager) mainAPIExporter(endpoints []Endpoint, projectName string) {
	filePath := fmt.Sprintf("%s/%s/api/main.go", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Error creating main file %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("package main\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"fmt\"\n")
	sb.WriteString("\t\"log\"\n")
	sb.WriteString("\t\"net/http\"\n")
	sb.WriteString("\t\"src/config\"\n")
	sb.WriteString("\t\"src/routes\"\n")
	sb.WriteString("\t\"src/middlewares\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("func main() {\n")
	sb.WriteString("\t// 1. Initialisation de la base de données\n")
	sb.WriteString("\tconfig.InitDB()\n\n")
	sb.WriteString("\t// 2. Initialisation du Router (Mux)\n")
	sb.WriteString("\tmux := http.NewServeMux()\n\n")

	// Récupération des groupes de routes (logique identique à routesAPIExporter)
	groups := make(map[string]bool)
	for _, ep := range endpoints {
		mName := "General"
		if len(ep.GetModel()) > 0 {
			mName = ep.GetModel()[0].GetNom()
		}
		groups[mName] = true
	}

	sb.WriteString("\t// 3. Enregistrement des routes par modèle\n")
	for groupName := range groups {
		cleanGroupName := strings.ReplaceAll(groupName, " ", "_")
		groupFuncName := strings.ToUpper(cleanGroupName[:1]) + cleanGroupName[1:]
		fmt.Fprintf(&sb, "\troutes.RegisterRoutes%s(mux)\n", groupFuncName)
	}

	sb.WriteString("\n\t// 4. Application du middleware CORS\n")
	sb.WriteString("\thandler := middlewares.CorsMiddleware(mux)\n\n")

	sb.WriteString("\t// 5. Lancement du serveur\n")
	sb.WriteString("\tport := \":8080\"\n")
	sb.WriteString("\tfmt.Printf(\"🚀 TurboStack API running on http://localhost%s\\n\", port)\n")
	sb.WriteString("\tlog.Fatal(http.ListenAndServe(port, handler))\n")
	sb.WriteString("}\n")

	file.WriteString(sb.String())
}

func (mgr *ProjectManager) setupStaticArch(name string) {
	projectPath := fmt.Sprintf("%s/%s/static/", config.PROJECT_DIR, name)
	dirList := []string{
		"css",
		"js",
		"assets",
	}
	for _, val := range dirList {
		config.CheckCreateDir(projectPath + val)
	}
}

func (mgr *ProjectManager) renderBlocksToHTML(blocks []any) string {
	var sb strings.Builder
	for _, b := range blocks {
		block, ok := b.(map[string]any)
		if !ok {
			continue
		}

		tag := fmt.Sprintf("%v", block["tag"])
		content := fmt.Sprintf("%v", block["content"])
		className := fmt.Sprintf("%v", block["className"])
		id := fmt.Sprintf("%v", block["id"])

		// Gestion des balises auto-fermantes
		if tag == "img" {
			sb.WriteString(fmt.Sprintf("<img src=\"%s\" class=\"%s\" data-id=\"%s\" />", content, className, id))
			continue
		}

		sb.WriteString(fmt.Sprintf("<%s class=\"%s\" data-id=\"%s\">", tag, className, id))
		sb.WriteString(content)

		if children, exists := block["children"].([]any); exists && len(children) > 0 {
			sb.WriteString(mgr.renderBlocksToHTML(children))
		}

		sb.WriteString(fmt.Sprintf("</%s>", tag))
	}
	return sb.String()
}

func (mgr *ProjectManager) ExporterStaticSite(Project Project) {
	projectName := Project.GetNom()
	site := Project.GetSiteStatique()
	mgr.setupStaticArch(projectName)

	// 1. Génération du CSS global
	cssPath := fmt.Sprintf("%s/static/css/style.css",  projectName)
	cssFile, _ := os.Create(cssPath)
	cssFile.WriteString("/* Generated by TurboStack */\nbody { margin: 0; font-family: sans-serif; }\n")

	// On pourrait ici itérer pour extraire tous les styles JSON des blocs
	cssFile.Close()

	// 2. Génération des pages HTML
	for _, page := range site.GetPages() {
		pageName := strings.ToLower(strings.ReplaceAll(page.GetNom(), " ", "_"))
		filePath := fmt.Sprintf("%s/static/%s.html", projectName, pageName)

		file, err := os.Create(filePath)
		if err != nil {
			continue
		}

		var sb strings.Builder
		sb.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n")
		sb.WriteString("\t<meta charset=\"UTF-8\">\n")
		fmt.Fprintf(&sb, "\t<title>%s</title>\n", page.GetNom())
		sb.WriteString("\t<link rel=\"stylesheet\" href=\"css/style.css\">\n")
		sb.WriteString("</head>\n<body>\n")

		// Conversion du contenu JSON en HTML
		content := page.GetContent()
		anyBlocks := make([]any, len(content))
		for i, v := range content {
			anyBlocks[i] = v
		}
		sb.WriteString(mgr.renderBlocksToHTML(anyBlocks))

		sb.WriteString("\n</body>\n</html>")

		file.WriteString(sb.String())
		file.Close()
	}

	fmt.Printf("Exportation du site statique terminée : %s\n", projectName)
}

func (mgr *ProjectManager) setupWebAppArch(name string) {
	projectPath := fmt.Sprintf("%s/web-app/", name)
	dirList := []string{
		"src/components",
		"src/pages",
		"src/services",
		"public",
	}
	for _, val := range dirList {
		config.CheckCreateDir(projectPath + val)
	}
}

func (mgr *ProjectManager) renderBlocksToJSX(blocks []any) string {
	var sb strings.Builder
	for _, b := range blocks {
		block, ok := b.(map[string]any)
		if !ok {
			continue
		}

		tag := fmt.Sprintf("%v", block["tag"])
		content := fmt.Sprintf("%v", block["content"])
		className := fmt.Sprintf("%v", block["className"])

		if tag == "img" {
			sb.WriteString(fmt.Sprintf("<img src=\"%s\" className=\"%s\" alt=\"\" />", content, className))
			continue
		}

		sb.WriteString(fmt.Sprintf("<%s className=\"%s\">", tag, className))
		sb.WriteString(content)

		if children, exists := block["children"].([]any); exists && len(children) > 0 {
			sb.WriteString(mgr.renderBlocksToJSX(children))
		}

		sb.WriteString(fmt.Sprintf("</%s>", tag))
	}
	return sb.String()
}

func (mgr *ProjectManager) ExporterWebApp(Project Project) {
	projectName := Project.GetNom()
	webApp := Project.GetWebApp()
	mgr.setupWebAppArch(projectName)

	// 1. Génération du package.json
	pkgPath := fmt.Sprintf("%s/web-app/package.json", projectName)
	pkgFile, _ := os.Create(pkgPath)
	pkgFile.WriteString(fmt.Sprintf(`{
  "name": "%s-frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.22.0",
    "lucide-react": "^0.344.0"
  },
  "devDependencies": {
    "@types/react": "^18.2.55",
    "@types/react-dom": "^18.2.19",
    "@vitejs/plugin-react": "^4.2.1",
    "autoprefixer": "^10.4.17",
    "postcss": "^8.4.35",
    "tailwindcss": "^3.4.1",
    "vite": "^5.1.0"
  }
}`, strings.ToLower(projectName)))
	pkgFile.Close()

	// 2. Génération du Service API
	svcPath := fmt.Sprintf("%s/web-app/src/services/api.js",  projectName)
	svcFile, _ := os.Create(svcPath)
	svcFile.WriteString(`const API_URL = "http://localhost:8080";

export const apiRequest = async (endpoint, method = "GET", data = null) => {
    const options = {
        method,
        headers: { "Content-Type": "application/json" }
    };
    if (data) options.body = JSON.stringify(data);
    const res = await fetch(${API_URL}${endpoint}, options);
    return res.json();
};`) 
	svcFile.Close()

	// 3. Génération des Composants
	for _, comp := range webApp.GetComposant() {
		compName := strings.ReplaceAll(comp.GetNom(), " ", "")
		filePath := fmt.Sprintf("%s/web-app/src/components/%s.jsx", projectName, compName)
		file, _ := os.Create(filePath)
		
		var sb strings.Builder
		fmt.Fprintf(&sb, "export default function %s() {\n\treturn (\n\t\t<>\n", compName)
		
		content := comp.GetContenu()
		anyBlocks := make([]any, len(content))
		for i, v := range content { anyBlocks[i] = v }
		sb.WriteString(mgr.renderBlocksToJSX(anyBlocks))
		
		sb.WriteString("\n\t\t</>\n\t);\n}")
		file.WriteString(sb.String())
		file.Close()
	}

	// 4. Génération des Pages
	for _, page := range webApp.GetPages() {
		pageName := strings.ReplaceAll(page.GetNom(), " ", "")
		filePath := fmt.Sprintf("%s/web-app/src/pages/%s.jsx", projectName, pageName)
		file, _ := os.Create(filePath)

		var sb strings.Builder
		sb.WriteString("import React from 'react';\n\n")
		fmt.Fprintf(&sb, "export default function %s() {\n\treturn (\n\t\t<div className=\"page-container\">\n", pageName)
		
		content := page.GetContent()
		anyBlocks := make([]any, len(content))
		for i, v := range content { anyBlocks[i] = v }
		sb.WriteString(mgr.renderBlocksToJSX(anyBlocks))

		sb.WriteString("\n\t\t</div>\n\t);\n}")
		file.WriteString(sb.String())
		file.Close()
	}

	// 5. Génération du Router (App.jsx)
	appPath := fmt.Sprintf("%s/web-app/src/App.jsx", projectName)
	appFile, _ := os.Create(appPath)
	var ab strings.Builder
	ab.WriteString("import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';\n")
	for _, page := range webApp.GetPages() {
		pName := strings.ReplaceAll(page.GetNom(), " ", "")
		fmt.Fprintf(&ab, "import %s from './pages/%s';\n", pName, pName)
	}
	ab.WriteString("\nfunction App() {\n\treturn (\n\t\t<Router>\n\t\t\t<Routes>\n")
	for _, page := range webApp.GetPages() {
		pName := strings.ReplaceAll(page.GetNom(), " ", "")
		uri := ""
		if uri == "" { uri = "/" }
		fmt.Fprintf(&ab, "\t\t\t\t<Route path=\"%s\" element={<%s />} />\n", uri, pName)
	}
	ab.WriteString("\t\t\t</Routes>\n\t\t</Router>\n\t);\n}\n\nexport default App;")
	appFile.WriteString(ab.String())
	appFile.Close()

	fmt.Printf("Exportation de la Web App terminée : %s\n", projectName)
}

// generateGormTags transforme les contraintes de l'UI en chaîne de tags GORM
func (mgr *ProjectManager) generateGormTags(field Champs) string {
	var tags []string

	for _, c := range field.GetConstraint() {
		cStr := strings.ToLower(fmt.Sprintf("%v", c))

		switch cStr {
		case "primary key":
			tags = append(tags, "primaryKey")
		case "unique":
			tags = append(tags, "unique")
		case "not null":
			tags = append(tags, "not null")
		case "autoincrement":
			tags = append(tags, "autoIncrement")
		}

		if strings.HasPrefix(cStr, "relation:") {
			// Pour les relations, on peut indexer le champ automatiquement
			tags = append(tags, "index")
		}
	}

	if field.GetDefaultValue() != nil && field.GetDefaultValue() != "" {
		tags = append(tags, fmt.Sprintf("default:%v", field.GetDefaultValue()))
	}

	if len(tags) > 0 {
		return fmt.Sprintf("`gorm:\"%s\"`", strings.Join(tags, ";"))
	}
	return ""
}
