package sqlgenerator

import (
	"fmt"
	"os"
	"strings"

	"github.com/MaminirinaEdwino/turbostack/src/config"
	"github.com/MaminirinaEdwino/turbostack/src/entity"
)

type Sqlgenerator struct {}

func (mgr *Sqlgenerator) postgresCRUDExporter(models []entity.Model, projectName string) {
	filePath := fmt.Sprintf("%s/%s/models/crud_queries.sql", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Erreur lors de la création du script CRUD %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("-- CRUD and Join Queries for PostgreSQL\n")
	sb.WriteString("-- Generated by TurboStack\n\n")

	for _, model := range models {
		tableName := strings.ToLower(model.GetNom())
		fields := model.GetAttributs()
		var colNames []string
		var pkName string

		for _, field := range fields {
			name := strings.ToLower(field.GetNom())
			colNames = append(colNames, name)
			for _, c := range field.GetConstraint() {
				if strings.ToLower(fmt.Sprintf("%v", c)) == "primary key" {
					pkName = name
				}
			}
		}

		if pkName == "" && len(colNames) > 0 {
			pkName = colNames[0]
		}

		fmt.Fprintf(&sb, "-- Queries for table: %s\n", tableName)

		// Create (Insert)
		placeholders := make([]string, len(colNames))
		for i := range colNames {
			placeholders[i] = fmt.Sprintf("$%d", i+1)
		}
		fmt.Fprintf(&sb, "-- Create\nINSERT INTO %s (%s) VALUES (%s);\n\n",
			tableName, strings.Join(colNames, ", "), strings.Join(placeholders, ", "))

		// Read (Select by ID)
		fmt.Fprintf(&sb, "-- Read\nSELECT * FROM %s WHERE %s = $1;\n\n", tableName, pkName)

		// Update
		var updates []string
		for i, col := range colNames {
			updates = append(updates, fmt.Sprintf("%s = $%d", col, i+1))
		}
		fmt.Fprintf(&sb, "-- Update\nUPDATE %s SET %s WHERE %s = $%d;\n\n",
			tableName, strings.Join(updates, ", "), pkName, len(colNames)+1)

		// Delete
		fmt.Fprintf(&sb, "-- Delete\nDELETE FROM %s WHERE %s = $1;\n\n", tableName, pkName)

		// Joins basés sur les contraintes de relation
		for _, field := range fields {
			for _, c := range field.GetConstraint() {
				cStr := strings.ToLower(fmt.Sprintf("%v", c))
				if strings.HasPrefix(cStr, "relation:") {
					target := strings.Split(cStr, ":")[1]
					targetParts := strings.Split(target, ".")
					if len(targetParts) == 2 {
						targetTable := targetParts[0]
						targetCol := targetParts[1]
						fmt.Fprintf(&sb, "-- Join with %s\nSELECT t1.*, t2.* FROM %s t1 JOIN %s t2 ON t1.%s = t2.%s;\n\n",
							targetTable, tableName, targetTable, strings.ToLower(field.GetNom()), targetCol)
					}
				}
			}
		}
		sb.WriteString("\n")
	}
	file.WriteString(sb.String())
}

func (mgr *Sqlgenerator) PostgresSQLExporter(models []entity.Model, projectName string) {
	filePath := fmt.Sprintf("%s/%s/models/init_db.sql", config.PROJECT_DIR, projectName)
	file, err := os.Create(filePath)
	if err != nil {
		fmt.Printf("Erreur lors de la création du script SQL %s : %v\n", filePath, err)
		return
	}
	defer file.Close()

	var sb strings.Builder
	sb.WriteString("-- SQL Schema for PostgreSQL\n")
	sb.WriteString("-- Generated by TurboStack\n\n")

	for _, model := range models {
		tableName := strings.ToLower(model.GetNom())
		sb.WriteString(fmt.Sprintf("CREATE TABLE IF NOT EXISTS %s (\n", tableName))

		var columns []string
		for i, field := range model.GetAttributs() {
			fName := strings.ToLower(field.GetNom())
			fType := strings.ToLower(field.GetType())

			// Détection de l'autoincrement pour le type SERIAL
			isSerial := false
			constraints := field.GetConstraint()
			for _, c := range constraints {
				if strings.ToLower(fmt.Sprintf("%v", c)) == "autoincrement" {
					isSerial = true
					break
				}
			}

			// Mapping des types PG
			pgType := "TEXT"
			switch fType {
			case "int":
				if isSerial {
					pgType = "SERIAL"
				} else {
					pgType = "INTEGER"
				}
			case "string":
				pgType = "VARCHAR(255)"
			}

			colDef := fmt.Sprintf("\t%s %s", fName, pgType)

			// Ajout des contraintes
			for _, c := range constraints {
				cStr := strings.ToLower(fmt.Sprintf("%v", c))
				switch cStr {
				case "primary key":
					colDef += " PRIMARY KEY"
				case "unique":
					colDef += " UNIQUE"
				case "not null":
					colDef += " NOT NULL"
				}

				if strings.HasPrefix(cStr, "relation:") {
					target := strings.Split(cStr, ":")[1] // ex: user.id
					targetParts := strings.Split(target, ".")
					if len(targetParts) == 2 {
						colDef += fmt.Sprintf(" REFERENCES %s(%s)", targetParts[0], targetParts[1])
					}
				}
			}
			columns = append(columns, colDef)
			_ = i
		}
		sb.WriteString(strings.Join(columns, ",\n"))
		sb.WriteString("\n);\n\n")
	}

	file.WriteString(sb.String())
}