import { Box, Form, FormInput, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6, ImageIcon, Link, Pilcrow, Square, Text, VideoIcon } from "lucide-react";
import { BsTextarea } from "react-icons/bs";

const sizeDistUnit = ["px", "em", "rem", "cm", "vh", "vw", "%"]

export const STYLE_CONTROLS = [
    { label: "Text-color", prop: "color", type: "color", group: "typo", conditions: [] },
    { conditions: [], label: "font-size", prop: "font-size", type: "number", placeholder: "e.g. 16", group: "typo", unite: ["px", "em", "rem", "cm", "%"] },
    { conditions: [], label: "text-align", prop: "text-align", type: "select", options: ["left", "center", "right", "justify"], group: "typo" },
    { conditions: [], label: "font-weight", prop: "font-weight", type: "select", options: ["normal", "bold", "100", "300", "500", "700", "900"], group: "typo" },
    { conditions: [], label: "background-color", prop: "background-color", type: "color", group: "background", reset: "none" },
    { conditions: [], group: "sizing", label: "Padding", prop: "padding", type: "number", placeholder: "e.g. 10", unite: ["px", "em", "rem", "cm", "%"] },
    { conditions: [], group: "sizing", label: "Margin", prop: "margin", type: "number", placeholder: "e.g. 0", unite: ["px", "em", "rem", "cm", "%"] },
    { conditions: [], label: "border-radius", prop: "border-radius", type: "number", placeholder: "e.g. 8", unite: ["px", "em", "rem", "cm", "%"], group: "border" },
    { conditions: [], group: "sizing", label: "Width", prop: "width", type: "number", placeholder: "100", unite: sizeDistUnit },
    { conditions: [], group: "sizing", label: "Height", prop: "height", type: "number", placeholder: "auto", unite: sizeDistUnit },
    { conditions: [], group: "display", label: "Display", prop: "display", type: "select", options: ["block", "inline-block", "flex", "grid", "none"] },
    { group: "display", label: "Flex dir", prop: "flex-direction", type: "select", options: ["row", "column", "row-wrap", "column-wrap"], conditions: ["display", "flex"] },
    { group: "display", label: "Flex gap", prop: "gap", type: "number", conditions: ["display", "flex"], unite: ["px", "em", "rem", "cm", "%"] },
    { group: "display", label: "Justify-content", prop: "justify-content", type: "select", conditions: ["display", "flex"], options: ["center", "start", "end", "flex-start", "flex-end", "space-between", "space-around", "space-evenly", "stretch"] },
    { group: "display", label: "Align-content", prop: "align-content", type: "select", conditions: ["display", "flex"], options: ["center", "start", "end", "flex-start", "flex-end"] },
    { group: "display", label: "Align-items", prop: "align-items", type: "select", conditions: ["display", "flex"], options: ["center", "start", "end", "flex-start", "flex-end"] },
    { conditions: [], group: "animation", label: "Animation delay", prop: "animation-delay", type: "number", unite: ["s", "ms"] },
    { conditions: [], group: "animation", label: "animation-direction", prop: "animation-direction", type: "select", options: ["normal", "alternate"] },
    { conditions: [], group: "animation", label: "Animation duration", prop: "animation-duration", type: "number", unite: ["s"] },
    { conditions: [], group: "animation", label: "animation-iteration-count", prop: "animation-iteration-count", type: "number" },
    { conditions: [], group: "animation", label: "animation-name", prop: "animation-name", type: "text" },
    { conditions: [], group: "animation", label: "animation-play-state", prop: "animation-play-state", type: "select", options: ["running", "pause"] },
    { conditions: [], group: "animation", label: "animaiton-timing-function", prop: "animation-timing-function", type: "select", options: ["ease", "linear", "easy-in", "ease-out", "ease-in-out"] },
    { conditions: [], group: "background", label: "backgroud-attachement", prop: "background-attachment", type: "select", options: ["fixed", "scroll"] },
    { conditions: [], group: "background", label: "backgroud-break", prop: "background-break", type: "select", options: ["bounding-box", "each-box", "continuous"] },
    { conditions: [], group: "background", label: "backgroud-clip", prop: "background-clip", type: "select", options: ["border-box", "padding-box", "content-box", "no-clip"] },
    { conditions: [], group: "background", label: "backgroud-image", prop: "background-image", type: "text" },
    { conditions: [], group: "background", label: "backgroud-origin", prop: "background-origin", type: "select", options: ["border-box", "padding-box", "content-box"] },
    { conditions: [], group: "background", label: "backgroud-position", prop: "background-position", type: "select", options: ["top left", "top center", "top right", "center left", "center center", "center right", "bottom left", "bottom center", "bottom right"] },
    { conditions: [], group: "background", label: "backgroud-repeat", prop: "background-repeat", type: "select", options: ["repeat", "repeat-x", "repeat-y", "no-repeat"] },
    { conditions: [], group: "background", label: "backgroud-size", prop: "background-size", type: "select", options: ["auto", "cover", "contain"] },
    { conditions: [], group: "border", label: "border-color", prop: "border-color", type: "color" },
    { conditions: [], group: "border", label: "border-width", prop: "border-width", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "border", label: "border-style", prop: "border-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { conditions: [], group: "border", label: "border-bottom-color", prop: "border-bottom-color", type: "color" },
    { conditions: [], group: "border", label: "border-bottom-width", prop: "border-bottom-width", type: "number", unite: ["px", "em", "rem", "cm", "%"] },
    { conditions: [], group: "border", label: "border-bottom-style", prop: "border-bottom-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { conditions: [], group: "border", label: "border-top-color", prop: "border-top-color", type: "color" },
    { conditions: [], group: "border", label: "border-top-width", prop: "border-top-width", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "border", label: "border-top-style", prop: "border-top-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { conditions: [], group: "border", label: "border-left-color", prop: "border-left-color", type: "color" },
    { conditions: [], group: "border", label: "border-left-width", prop: "border-left-width", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "border", label: "border-left-style", prop: "border-left-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { conditions: [], group: "border", label: "border-right-color", prop: "border-right-color", type: "color" },
    { conditions: [], group: "border", label: "border-right-width", prop: "border-right-width", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "border", label: "border-right-style", prop: "border-right-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { conditions: [], group: "sizing", label: "margin-top", prop: "margin-top", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", label: "margin-bottom", prop: "margin-bottom", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", label: "margin-left", prop: "margin-left", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", label: "margin-right", prop: "margin-right", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", prop: "padding-top", label: "padding-top", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", prop: "padding-bottom", label: "padding-bottom", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", prop: "padding-left", label: "padding-left", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", prop: "padding-right", label: "padding-right", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "sizing", prop: "overflow", label: "overflow", type: "select", options: ["visible", "hidden", "scroll", "auto", "no-display", "no-content"] },
    { conditions: [], group: "sizing", prop: "overflow-x", label: "overflow-x", type: "select", options: ["visible", "hidden", "scroll", "auto", "no-display", "no-content"] },
    { conditions: [], group: "sizing", prop: "overflow-y", label: "overflow-y", type: "select", options: ["visible", "hidden", "scroll", "auto", "no-display", "no-content"] },
    { conditions: [], group: "sizing", prop: "overflow-style", label: "overflow-style", type: "select", options: ["auto", "marquee-line", "mar-quee-block"] },
    { conditions: [], group: "sizing", prop: "box-sizing", label: "box-sizing", type: "select", options: ["border-box", "content-box", "inherit", "initial"] },
    { conditions: [], group: "outline", prop: "outline-color", label: "outline-color", type: "color" },
    { conditions: [], group: "outline", prop: "outline-offset", label: "outline-offset", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "outline", prop: "outline-width", label: "outline-width", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "outline", prop: "outline-style", label: "outline-style", type: "select", options: ["none", "groove", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { conditions: [], group: "text", prop: "Direction", label: "Direction", type: "select", options: ["ltr", "rtl", "inherit"] },
    { conditions: [], group: "text", prop: "hanging-punctuation", label: "hanging-punctuation", type: "select", options: ["none", "start", "end", "end-edge"] },
    { conditions: [], group: "text", prop: "letter-spacing", label: "letter-spacing", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "text", prop: "text-indent", label: "text-indent", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "text", prop: "punctuation-trim", label: "punctuation-trim", type: "select", options: ["none", "start", "end", "adja-cent"] },
    { conditions: [], group: "text", prop: "text-align", label: "text-align", type: "select", options: ["center", "start", "end", "left", "right", "justify"] },
    { conditions: [], group: "text", prop: "text-align-last", label: "text-align-last", type: "select", options: ["center", "start", "end", "left", "right", "justify"] },
    { conditions: [], group: "text", prop: "text-decoration", label: "text-decoration", type: "select", options: ["none", "underline", "overline", "blink"] },
    { conditions: [], group: "text", prop: "text-justify", label: "text-justify", type: "select", options: ["auto", "inter-word", "inter-ideograph", "inter-cluster", "distribute", "kashida", "tibetan"] },
    { conditions: [], group: "transition", prop: "transition-properties", label: "transition", type: "select", options: ["all", "none"] },
    { conditions: [], group: "transition", prop: "transition-time", label: "transition-time", type: "number", unite: ["s", "ms"] },
    { conditions: [], group: "transition", prop: "transition-delay", label: "transition-delay", type: "number", unite: ["s", "ms"] },
    { conditions: [], group: "transition", prop: "transition-timing-function", label: "transition", type: "select", options: ["ease", "linear", "ease-in", "ease-out", "ease-in-out"] },
    { conditions: [], group: "box-shadow", prop: "box-shadow", label: "box-shadow", type: "text", placeholder: "inset 0px 0px 0px 0px #ffffff" },
    { conditions: [], group: "position", prop: "position", label: "Position", type: "select", options: ["sticky", "relative", "fixed", "absolute"] },
    { conditions: [], group: "position", prop: "top", label: "Top", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "position", prop: "bottom", label: "Bottom", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "position", prop: "left", label: "Left", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "position", prop: "right", label: "Right", type: "number", unite: sizeDistUnit },
    { conditions: [], group: "position", prop: "z-index", label: "z-index", type: "number" },
];

export const BLOCK_TYPES = [
    { label: "Div", tag: "div", icon: <Box size={14} />, defaultContent: "Container", group: "container" },
    { label: "Section", tag: "section", icon: <Box size={14} />, defaultContent: "Section", group: "container" },
    { label: "Main", tag: "main", icon: <Box size={14} />, defaultContent: "Main", group: "container" },
    { label: "Aside", tag: "aside", icon: <Box size={14} />, defaultContent: "Aside", group: "container" },
    { label: "Heading 1", tag: "h1", icon: <Heading1 size={14} />, defaultContent: "Heading 1", group: "heading" },
    { label: "Heading 2", tag: "h2", icon: <Heading2 size={14} />, defaultContent: "Heading 2", group: "heading" },
    { label: "Heading 3", tag: "h3", icon: <Heading3 size={14} />, defaultContent: "Heading 3", group: "heading" },
    { label: "Heading 4", tag: "h4", icon: <Heading4 size={14} />, defaultContent: "Heading 4", group: "heading" },
    { label: "Heading 5", tag: "h5", icon: <Heading5 size={14} />, defaultContent: "Heading 5", group: "heading" },
    { label: "Heading 6", tag: "h6", icon: <Heading6 size={14} />, defaultContent: "Heading 6", group: "heading" },
    { label: "Paragraphe", tag: "p", icon: <Pilcrow size={14} />, defaultContent: "Paragraphe...", group: "text" },
    { label: "Link", tag: "a", icon: <Link size={14} />, defaultContent: "Click here", defaultHref: "/", group: "link" },
    { label: "Image", tag: "img", icon: <ImageIcon size={14} />, defaultContent: "https://via.placeholder.com/800x400", group: "media" },
    { label: "Video", tag: "video", icon: <VideoIcon size={14} />, defaultContent: "https://via.placeholder.com/800x400", group: "media" },
    { label: "Button", tag: "button", icon: <Square size={14} />, defaultContent: "Click here", group: "button" },
    { label: "Label", tag: "label", icon: <Text size={14} />, defaultContent: "label", group: "text", attr: [{ name: "for", type: "text", defaultContent: "text" }] },
    { label: "Textarea", tag: "textarea", icon: <BsTextarea size={14} />, defaultContent: "textarea", group: "text" },
    { label: "Form", tag: "form", icon: <Form size={14} />, defaultContent: "Post form", group: "form" },
    { label: "Input (text)", tag: "input", icon: <FormInput size={14} />, inputType: "text", group: "form" },
    { label: "Input (int)", tag: "input", icon: <FormInput size={14} />, inputType: "number", group: "form" },
    { label: "Input (email)", tag: "input", icon: <FormInput size={14} />, inputType: "email", group: "form" },
    { label: "Input (password)", tag: "input", icon: <FormInput size={14} />, inputType: "password", group: "form" },
];
export const GROUP_LIST = ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"]

export const TAG_STYLE_GROUPS = {
    form: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    h1: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    h2: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    h3: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    h4: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    h5: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    h6: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    section: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    main: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    aside: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    p: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    span: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    a: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    button: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    label: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    textarea: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    div: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    img: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    page: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    generic: ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    "textarea:hover": ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    "div:hover": ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    "button:hover": ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
    "input": ["typo", "background", "display", "animation", "border", "sizing", "outline", "text", "transition", "box-shadow", "position"],
};
// export const TAG_STYLE_GROUPS = {
//     h1: ["color", "font-size", "text-align", "font-weight", "margin"],
//     h2: ["color", "font-size", "text-align", "font-weight", "margin"],
//     p: ["color", "font-size", "text-align", "margin"],
//     a: ["color", "font-size", "font-weight", "background-color", "padding", "border-radius"],
//     button: ["color", "font-size", "font-weight", "background-color", "padding", "border-radius", "margin"],
//     div: ["background-color", "padding", "margin", "border-radius", "width", "height", "display", "flex-direction"],
//     img: ["width", "height", "border-radius", "margin", "display"],
//     page: ["color", "font-size", "background-color", "padding", "margin"],
//     generic: ["color", "font-size", "text-align", "font-weight", "background-color", "padding", "margin", "border-radius", "width", "height", "display"]
// };

export const PSEUDO_CLASS = [
    "active", "focus", "visited", "hover", "link", "checked", "selection", "lang", "nth-child(n)", "nth-last-child(n)", "first-child", "only-child", "last-child", "nth-last-of-type()", "empty", "root", "not(x)", "target"
]