import { Box, Heading1, Heading2, Heading3, Heading4, Heading5, Heading6, ImageIcon, Link, Pilcrow, Square, Text, VideoIcon } from "lucide-react";
import { BsTextarea } from "react-icons/bs";

export const STYLE_CONTROLS = [
    { label: "Texte", prop: "color", type: "color", group: "typo" },
    { label: "Taille", prop: "font-size", type: "number", placeholder: "e.g. 16", group: "typo" },
    { label: "Align", prop: "text-align", type: "select", options: ["left", "center", "right", "justify"], group: "type" },
    { label: "Gras", prop: "font-weight", type: "select", options: ["normal", "bold", "100", "300", "500", "700", "900"], group: "type" },
    { label: "Fond", prop: "background-color", type: "color", group: "background" },
    { group: "sizing", label: "Padding", prop: "padding", type: "number", placeholder: "e.g. 10" },
    { group: "sizing", label: "Marge", prop: "margin", type: "number", placeholder: "e.g. 0" },
    { label: "Arrondi", prop: "border-radius", type: "number", placeholder: "e.g. 8" },
    { group: "sizing", label: "Largeur", prop: "width", type: "number", placeholder: "100" },
    { group: "sizing", label: "Hauteur", prop: "height", type: "number", placeholder: "auto" },
    { group: "display", label: "Display", prop: "display", type: "select", options: ["block", "inline-block", "flex", "grid", "none"] },
    { group: "display", label: "Flex dir", prop: "flex-direction", type: "select", options: ["row", "column"] },
    { group: "animation", label: "Animation delay", prop: "animation-delay", type: "number", unite: ["s"] },
    { group: "animation", label: "animation-­direction", prop: "animation-direction", type: "select", options: ["normal", "alternate"] },
    { group: "animation", label: "Animation duration", prop: "animation-duration", type: "number", unite: ["s"] },
    { group: "animation", label: "animation-iteration-count", prop: "animation-iteration-count", type: "number" },
    { group: "animation", label: "animation-name", prop: "animation-name", type: "text" },
    { group: "animation", label: "animation-play-state", prop: "animation-play-state", type: "select", options: ["running", "pause"] },
    { group: "animation", label: "animaiton-timing-function", prop: "animation-timing-function", type: "select", options: ["ease", "linear", "easy-in", "ease-out", "ease-in-out"] },
    { group: "background", label: "backgroud-attachement", prop: "background-attachment", type: "select", options: ["fixed", "scroll"] },
    { group: "background", label: "backgroud-break", prop: "background-break", type: "select", options: ["bounding-box", "each-box", "continuous"] },
    { group: "background", label: "backgroud-clip", prop: "background-clip", type: "select", options: ["border-box", "padding-box", "content-box", "no-clip"] },
    { group: "background", label: "backgroud-image", prop: "background-image", type: "text" },
    { group: "background", label: "backgroud-origin", prop: "background-origin", type: "select", options: ["border-box", "padding-box", "content-box"] },
    { group: "background", label: "backgroud-position", prop: "background-position", type: "select", options: ["top left", "top center", "top right", "center left", "center center", "center right", "bottom left", "bottom center", "bottom right"] },
    { group: "background", label: "backgroud-repeat", prop: "background-repeat", type: "select", options: ["repeat", "repeat-x", "repeat-y", "no-repeat"] },
    { group: "background", label: "backgroud-size", prop: "background-size", type: "select", options: ["auto", "cover", "contain"] },
    { group: "border", label: "border-color", prop: "border-color", type: "color" },
    { group: "border", label: "border-width", prop: "border-width", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "border", label: "border-style", prop: "border-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { group: "border", label: "border-bottom-color", prop: "border-bottom-color", type: "color" },
    { group: "border", label: "border-bottom-width", prop: "border-bottom-width", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "border", label: "border-bottom-style", prop: "border-bottom-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { group: "border", label: "border-top-color", prop: "border-top-color", type: "color" },
    { group: "border", label: "border-top-width", prop: "border-top-width", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "border", label: "border-top-style", prop: "border-top-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { group: "border", label: "border-left-color", prop: "border-left-color", type: "color" },
    { group: "border", label: "border-left-width", prop: "border-left-width", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "border", label: "border-left-style", prop: "border-left-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { group: "border", label: "border-right-color", prop: "border-right-color", type: "color" },
    { group: "border", label: "border-right-width", prop: "border-right-width", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "border", label: "border-right-style", prop: "border-right-style", type: "select", options: ["none", "hidden", "solid", "double", "dashed", "dotted", "inset", "outset", "ridge"] },
    { group: "sizing", label: "margin-top", prop: "margin-top", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", label: "margin-bottom", prop: "margin-bottom", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", label: "margin-left", prop: "margin-left", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", label: "margin-right", prop: "margin-right", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", prop: "margin-top", label: "padding-top", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", prop: "margin-bottom", label: "padding-bottom", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", prop: "margin-left", label: "padding-left", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", prop: "margin-right", label: "padding-right", type: "number", unite: ["px", "em", "rem", "cm"] },
    { group: "sizing", prop: "overflow", label: "overflow", type: "select", options: ["visible", "hidden", "scroll", "auto", "no-display", "no-content"] },
    { group: "sizing", prop: "overflow-x", label: "overflow-x", type: "select", options: ["visible", "hidden", "scroll", "auto", "no-display", "no-content"] },
    { group: "sizing", prop: "overflow-y", label: "overflow-y", type: "select", options: ["visible", "hidden", "scroll", "auto", "no-display", "no-content"] },
    { group: "sizing", prop: "overflow-style", label: "overflow-style", type: "select", options: ["auto", "marquee-line", "mar-quee-block"] }
];

export const BLOCK_TYPES = [
    { label: "Div", tag: "div", icon: <Box size={14} />, defaultContent: "Container", group: "container" },
    { label: "Section", tag: "section", icon: <Box size={14} />, defaultContent: "Section", group: "container" },
    { label: "Main", tag: "main", icon: <Box size={14} />, defaultContent: "Main", group: "container" },
    { label: "Aside", tag: "aside", icon: <Box size={14} />, defaultContent: "Aside", group: "container" },
    { label: "Heading 1", tag: "h1", icon: <Heading1 size={14} />, defaultContent: "Heading 1", group: "heading" },
    { label: "Heading 2", tag: "h2", icon: <Heading2 size={14} />, defaultContent: "Heading 2", group: "heading" },
    { label: "Heading 3", tag: "h3", icon: <Heading3 size={14} />, defaultContent: "Heading 3", group: "heading" },
    { label: "Heading 4", tag: "h4", icon: <Heading4 size={14} />, defaultContent: "Heading 4", group: "heading" },
    { label: "Heading 5", tag: "h5", icon: <Heading5 size={14} />, defaultContent: "Heading 5", group: "heading" },
    { label: "Heading 6", tag: "h6", icon: <Heading6 size={14} />, defaultContent: "Heading 6", group: "heading" },
    { label: "Paragraphe", tag: "p", icon: <Pilcrow size={14} />, defaultContent: "Paragraphe...", group: "text" },
    { label: "Link", tag: "a", icon: <Link size={14} />, defaultContent: "Click here", defaultHref: "/", group: "link" },
    { label: "Image", tag: "img", icon: <ImageIcon size={14} />, defaultContent: "https://via.placeholder.com/800x400", group: "media" },
    { label: "Video", tag: "video", icon: <VideoIcon size={14} />, defaultContent: "https://via.placeholder.com/800x400", group: "media" },
    { label: "Button", tag: "button", icon: <Square size={14} />, defaultContent: "Click here", group: "button" },
    { label: "Label", tag: "label", icon: <Text size={14} />, defaultContent: "label", group: "text", attr: [{ name: "for", type: "text", defaultContent: "text" }] },
    { label: "Textarea", tag: "textarea", icon: <BsTextarea size={14} />, defaultContent: "textarea", group: "text" },
];

export const TAG_STYLE_GROUPS = {
    h1: ["color", "font-size", "text-align", "font-weight", "margin"],
    h2: ["color", "font-size", "text-align", "font-weight", "margin"],
    p: ["color", "font-size", "text-align", "margin"],
    a: ["color", "font-size", "font-weight", "background-color", "padding", "border-radius"],
    button: ["color", "font-size", "font-weight", "background-color", "padding", "border-radius", "margin"],
    div: ["background-color", "padding", "margin", "border-radius", "width", "height", "display", "flex-direction"],
    img: ["width", "height", "border-radius", "margin", "display"],
    page: ["color", "font-size", "background-color", "padding", "margin"],
    generic: ["color", "font-size", "text-align", "font-weight", "background-color", "padding", "margin", "border-radius", "width", "height", "display"]
};